// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://urwhtkkvnmdocmjkqerx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVyd2h0a2t2bm1kb2NtamtxZXJ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2ODA2MDYsImV4cCI6MjA2MjI1NjYwNn0.ci5-MLIpAyd3-JHZrsvO8wwOZ61ZZYvpQGQf0VlbjQ0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);